# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret
    namespace: networking
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:ODn3SgORdaoDKMDcJ4NbY70uzA82EUgvwU3oz4fub3prZ08xFQRB5OFdUN+3CPNvDB7Cf/C06QTTO/cvGg==,iv:FtBy0P2k/Lc9kvpqEf3Cm6ROjvJc6nCXauRQydTvjgY=,tag:UQE/rAiPesJKPHecdvsgbQ==,type:str]
sops:
    age:
        - recipient: age1k8xaut2yz4ttudhtwxk0jf8ckrav2rugjup5vyqu3tyzp2lxhgxq93u2mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2azJHYWh1WUtWbGhRamM4
            VXZCcnRmUVlpSE0yNmFMTmppT2ZZZjhqL0ZnCmsva2ZOSVVRNWhIQjF1NHgyN1F2
            aHZkSlM0ajRlUDhIdnpHa09jWUtxdjQKLS0tIEppQmlVTFNYdkM3ejVYaWxwQm9T
            ZndUS1NPQy8vd3RsWjBCME9xMHB3VGsK7eIPpeOQJKOcLfdGd5xSyjaVD01w77kX
            O8w0g//KmkKHPFba7GwCQHil3J9Qsv4QmMKKFHnrjs3kGHVlBPpLkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T10:40:46Z"
    mac: ENC[AES256_GCM,data:FQJMQ9f2lAD0b3+g8P6FgRkxaQNeniuvHBiD/+siS068dvLD5EKjkEuA4a+NGnFFrgJMVS8/ahmTpi/C0ziS0y1+wx8M0T95GLWM+hEc8g4pHkvZT5G8YKqM+jlyF46HuTI+Sv7IBdP5Dp+p790vyYdxrqm6wPzxM8IC+UIvvkA=,iv:tbFM9iUOAnUVqD7Zmig8Ni4r3g5eTR3wSLUPkQAMnnw=,tag:Uvv45HMDcgq8mFW8seRoWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
